import colors from "./Colors";
import themeFontSize from "./themeFontSizes"

export default {
  text: {
    fontFamily: "PoppinsLight",
    fontSize: themeFontSize.small,
    color: colors.black,
  },
  h1: {
    fontFamily: "PoppinsRegular",
    fontSize: themeFontSize.xxl,
  },
  h2: {
    fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.xl,
  },
  h3: {
    fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.large,
  },
  h4: {
    fontFamily: "PoppinsRegular",
    fontSize: themeFontSize.medium,
  },
  h5: {
    fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.small,
  },
  h6: {
    fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.xsmall,
  },
  welcomeContainer:{
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      marginVertical: "15%",
      marginHorizontal: "5%",
  },
  themeContainer:{
    flex: 1,
    paddingHorizontal: "5%",
    marginTop: "5%",
    marginBottom: "15%",
  },
  blueButton: {
    backgroundColor: colors.black,
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 6,
    paddingBottom: 6,
    margin: 0,
    color: "#fff",
    borderRadius: 50,
  },
  blueButtonMain: {
    backgroundColor: colors.black,
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 8,
    paddingBottom: 8,
    margin: 0,
    color: "#fff",
    borderRadius: 50,
  },
  blueBtnText: {
    color: "#fff",
    fontFamily: "PoppinsMedium",
    fontSize: themeFontSize.large,
    textAlign: "center",
  },
  fullWidthBtn:{
    width: "100%",
    marginTop: 10
    },
  input: {
    height: 40,
    maxWidth: 595,
    width: "100%",
    marginBottom: 12,
    borderColor: "#CFD8EB",
    borderWidth: 2,
    backgroundColor: "#FFFFFF",
    borderRadius: 50,
    fontSize: themeFontSize.medium,
    color: colors.black,
    paddingLeft: 25,
    paddingRight: 25,
    paddingTop: 8,
    paddingBottom: 8,
    justifyContent: "center",
  },
  dropdown: {
    width: "100%",
    fontSize: themeFontSize.medium,
    color: "#3F466F",
    backgroundColor: "#FFFFFF",
  },
  dropdownWrapper: {
    height: 40,
    flexDirection: "row",
    position: "relative",
    borderColor: "#CFD8EB",
    borderWidth: 2,
    borderRadius: 50,
    backgroundColor: "#FFFFFF",
    paddingLeft: 16,
    paddingRight: 8,
    paddingTop: 8,
    paddingBottom: 8,
    marginBottom: 8,
  },
  bottomDrop: {
    position: "absolute",
    right: 13,
    width: 13,
    height: 13,
    top: 12,
    resizeMode: "contain",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  shadow: {
    shadowColor: "#ADB6D9",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.38,
    shadowRadius: 5,
    elevation: 5,
  },
  topBar: {
    flexDirection: "row",
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
    paddingTop: "10%",
    paddingBottom: 10,
    backgroundColor: "#fff",
    position: "relative",
    zIndex: 1,
  },
  backbtn: {
    position: "absolute",
    left: 20,
    bottom: 12,
    zIndex: 2,
  },
  backArrow: {
    width: 20,
    height: 20,
    zIndex: 2,
  },
  nextbtn: {
    position: "absolute",
    right: 20,
    bottom: 12,
    zIndex: 2,
  },
  basketIcon: {
    width: 22,
    height: 22,
  },
  container: {
    maxWidth: 595,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  productQuantity: {
    borderWidth: 2,
    borderColor: "#CFD8EB",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 15,
    backgroundColor: colors.white,
  },
  quantityIcon: {
    paddingHorizontal: 12,
  },
  minusIcon: {
    width: 15,
    height: 15,
    resizeMode: "contain",
  },
  plusIcon: {
    width: 15,
    height: 15,
    resizeMode: "contain",
  },
  quantity: {
    borderLeftWidth: 2,
    borderRightWidth: 2,
    borderColor: "#CFD8EB",
  },
  quantityText: {
    paddingHorizontal: 5,
    textAlign: "center",
  },
  pickerText: {
    fontSize: themeFontSize.medium,
    color: colors.black,
  },
  catBtn: {
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderRadius: 50,
    borderColor: "#3F466F",
    paddingTop: 2,
    paddingBottom: 2,
    paddingLeft: 15,
    paddingRight: 15,
  },
  categoriesList: {
    flexDirection: "row",
    marginLeft: 10,
  },
  filterList: {
    marginTop: 5,
    marginBottom: 20,
  },

  editDelButton: {
    backgroundColor: colors.black,
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    borderRadius: 50,
    paddingLeft: 18,
    paddingRight: 18,
    paddingTop: 2,
  },
  rightCol: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    width: "53%",
  },
  active: {
    backgroundColor: colors.black,
    borderColor: colors.black,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalView: {
    margin: 20,
    backgroundColor: "white",
    padding: 35,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  keypadButton: {
    width: "32%",
    backgroundColor: "#ffffff",
    padding: 10,
    height: 60,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: 2,
    marginHorizontal: 2,
  },
  tabIcon :{
    width: 25,
    height: 25,
    tintColor: "#292929",
  },
  BTposBtn:{
    width: 60,
    height: 60,
    position: "relative",
    borderRadius: 30,
    backgroundColor: "#292929",
    borderColor: "#fff",
    borderWidth: 2,
  },
  posBtn:{
    top: -20,
    justifyContent: "center",
    alignItems: "center",
  },
  posIcon :{
    tintColor: "#fff",
  }
};
